"""Add comprehensive course information fields and instructor model

Revision ID: 102d4f8105a4
Revises: add_task_attempt_limits
Create Date: 2025-09-04 01:45:47.785668

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "102d4f8105a4"
down_revision: Union[str, None] = "add_task_attempt_limits"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course_instructors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("image", sa.String(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("social_links", sa.JSON(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_course_instructors_course_order", "course_instructors", ["course_id", "display_order"], unique=False
    )
    op.create_index(op.f("ix_course_instructors_id"), "course_instructors", ["id"], unique=False)
    op.add_column("courses", sa.Column("course_overview", sa.Text(), nullable=True))
    op.add_column("courses", sa.Column("learning_objectives", sa.JSON(), nullable=True))
    op.add_column("courses", sa.Column("requirements", sa.JSON(), nullable=True))
    op.add_column("courses", sa.Column("target_audience", sa.JSON(), nullable=True))
    op.add_column("courses", sa.Column("duration_weeks", sa.Integer(), nullable=True))
    op.add_column("courses", sa.Column("difficulty_level", sa.String(length=20), nullable=True))
    op.add_column("courses", sa.Column("course_image", sa.String(), nullable=True))
    op.drop_index("idx_tasks_attempt_strategy", table_name="tasks")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_tasks_attempt_strategy", "tasks", ["attempt_strategy"], unique=False)
    op.drop_column("courses", "course_image")
    op.drop_column("courses", "difficulty_level")
    op.drop_column("courses", "duration_weeks")
    op.drop_column("courses", "target_audience")
    op.drop_column("courses", "requirements")
    op.drop_column("courses", "learning_objectives")
    op.drop_column("courses", "course_overview")
    op.drop_index(op.f("ix_course_instructors_id"), table_name="course_instructors")
    op.drop_index("idx_course_instructors_course_order", table_name="course_instructors")
    op.drop_table("course_instructors")
    # ### end Alembic commands ###
