"""add student form submissions table

Revision ID: 27c8b3704cb5
Revises: 26779a9574cf
Create Date: 2025-08-09 04:39:35.874127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27c8b3704cb5'
down_revision: Union[str, None] = '26779a9574cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_form_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('programming_experience', sa.String(), nullable=False),
    sa.Column('other_language', sa.String(), nullable=True),
    sa.Column('operating_system', sa.String(), nullable=False),
    sa.Column('software_installation', sa.String(), nullable=False),
    sa.Column('python_confidence', sa.Integer(), nullable=False),
    sa.Column('problem_solving_approach', sa.JSON(), nullable=False),
    sa.Column('learning_preferences', sa.JSON(), nullable=False),
    sa.Column('new_device_approach', sa.String(), nullable=False),
    sa.Column('study_time_commitment', sa.String(), nullable=False),
    sa.Column('homework_schedule', sa.String(), nullable=False),
    sa.Column('preferred_study_times', sa.JSON(), nullable=False),
    sa.Column('study_organization', sa.String(), nullable=False),
    sa.Column('help_seeking_preference', sa.String(), nullable=False),
    sa.Column('additional_comments', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_form_submissions_id'), 'student_form_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_student_form_submissions_user_id'), 'student_form_submissions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_form_submissions_user_id'), table_name='student_form_submissions')
    op.drop_index(op.f('ix_student_form_submissions_id'), table_name='student_form_submissions')
    op.drop_table('student_form_submissions')
    # ### end Alembic commands ###
