"""Add task_attempt to AIFeedback

Revision ID: 6ea2f46bde24
Revises: 7fab4054c950
Create Date: 2024-10-27 23:12:36.832911

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ea2f46bde24"
down_revision: Union[str, None] = "7fab4054c950"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ai_feedback", sa.Column("task_attempt_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "ai_feedback", "task_attempts", ["task_attempt_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "ai_feedback", type_="foreignkey")
    op.drop_column("ai_feedback", "task_attempt_id")
    # ### end Alembic commands ###
