"""Add language field to Course model

Revision ID: 774f0fe90614
Revises: b266f6a1169a
Create Date: 2025-09-05 10:46:27.101137

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "774f0fe90614"
down_revision: Union[str, None] = "b266f6a1169a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("courses", sa.Column("language", sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("courses", "language")
    # ### end Alembic commands ###
