"""add_telegram_user_info_to_link_tokens

Revision ID: 965b7a4781cb
Revises: 12c8a826cf5e
Create Date: 2025-08-11 03:16:44.961320

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "965b7a4781cb"
down_revision: Union[str, None] = "12c8a826cf5e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("telegram_link_tokens", sa.Column("telegram_username", sa.String(), nullable=True))
    op.add_column("telegram_link_tokens", sa.Column("first_name", sa.String(), nullable=True))
    op.add_column("telegram_link_tokens", sa.Column("last_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("telegram_link_tokens", "last_name")
    op.drop_column("telegram_link_tokens", "first_name")
    op.drop_column("telegram_link_tokens", "telegram_username")
    # ### end Alembic commands ###
