"""Sort topics inside the lesson

Revision ID: a3ca12b1a9e2
Revises: f74cdb609289
Create Date: 2024-10-25 16:14:24.982384

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a3ca12b1a9e2"
down_revision: Union[str, None] = "f74cdb609289"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
