"""Add enrollment management fields to Course model

Revision ID: b266f6a1169a
Revises: 102d4f8105a4
Create Date: 2025-09-04 03:15:59.316364

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b266f6a1169a"
down_revision: Union[str, None] = "102d4f8105a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("courses", sa.Column("enrollment_open_date", sa.DateTime(), nullable=True))
    op.add_column("courses", sa.Column("enrollment_close_date", sa.DateTime(), nullable=True))
    op.add_column("courses", sa.Column("max_enrollments", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("courses", "max_enrollments")
    op.drop_column("courses", "enrollment_close_date")
    op.drop_column("courses", "enrollment_open_date")
    # ### end Alembic commands ###
