"""Add dynamic task generation support

Revision ID: caab59d83def
Revises: add_performance_indexes
Create Date: 2025-08-17 13:48:40.953708

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "caab59d83def"
down_revision: Union[str, None] = "add_performance_indexes"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_ai_feedback_user_task_created", table_name="ai_feedback")
    op.drop_index("idx_course_enrollments_user_course", table_name="course_enrollments")
    op.drop_index("idx_lessons_course_order", table_name="lessons")
    op.drop_index("idx_task_attempts_task_successful", table_name="task_attempts")
    op.drop_index("idx_task_attempts_user_submitted", table_name="task_attempts")
    op.drop_index("idx_task_solutions_user_task_completed", table_name="task_solutions")
    op.drop_index("idx_tasks_topic_covering", table_name="tasks")
    op.drop_index("idx_tasks_topic_order", table_name="tasks")
    op.drop_index("idx_topics_lesson_order", table_name="topics")
    op.drop_index("idx_users_internal_user_id", table_name="users")
    op.drop_index("idx_users_status", table_name="users")
    op.drop_index("idx_users_telegram_id", table_name="users")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_users_telegram_id", "users", ["telegram_user_id"], unique=False)
    op.create_index("idx_users_status", "users", ["status"], unique=False)
    op.create_index("idx_users_internal_user_id", "users", ["internal_user_id"], unique=False)
    op.create_index("idx_topics_lesson_order", "topics", ["lesson_id", "topic_order"], unique=False)
    op.create_index("idx_tasks_topic_order", "tasks", ["topic_id", "order"], unique=False)
    op.create_index("idx_tasks_topic_covering", "tasks", ["topic_id", "type", "order"], unique=False)
    op.create_index(
        "idx_task_solutions_user_task_completed", "task_solutions", ["user_id", "task_id", "completed_at"], unique=False
    )
    op.create_index("idx_task_attempts_user_submitted", "task_attempts", ["user_id", "submitted_at"], unique=False)
    op.create_index(
        "idx_task_attempts_task_successful", "task_attempts", ["task_id", "is_successful", "submitted_at"], unique=False
    )
    op.create_index("idx_lessons_course_order", "lessons", ["course_id", "lesson_order"], unique=False)
    op.create_index(
        "idx_course_enrollments_user_course",
        "course_enrollments",
        ["user_id", "course_id", "enrolled_at"],
        unique=False,
    )
    op.create_index(
        "idx_ai_feedback_user_task_created", "ai_feedback", ["user_id", "task_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###
