"""Remove textbooks

Revision ID: e79737401da2
Revises: ffafed6f5ab6
Create Date: 2024-10-20 14:53:41.755180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e79737401da2'
down_revision: Union[str, None] = 'ffafed6f5ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop indexes and table for textbookchapters first
    op.drop_index('ix_textbookchapters_chapter_link', table_name='textbookchapters')
    op.drop_index('ix_textbookchapters_chapter_title', table_name='textbookchapters')
    op.drop_index('ix_textbookchapters_content_file_md', table_name='textbookchapters')
    op.drop_index('ix_textbookchapters_id', table_name='textbookchapters')
    op.drop_index('ix_textbookchapters_title', table_name='textbookchapters')
    op.drop_table('textbookchapters')

    # Drop textbooks table with CASCADE to handle dependencies
    op.execute('DROP TABLE textbooks CASCADE')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('textbookchapters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content_file_md', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('textbook_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chapter_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('chapter_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['textbook_id'], ['textbooks.id'], name='textbookchapters_textbook_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='textbookchapters_pkey')
    )
    op.create_index('ix_textbookchapters_title', 'textbookchapters', ['title'], unique=False)
    op.create_index('ix_textbookchapters_id', 'textbookchapters', ['id'], unique=False)
    op.create_index('ix_textbookchapters_content_file_md', 'textbookchapters', ['content_file_md'], unique=False)
    op.create_index('ix_textbookchapters_chapter_title', 'textbookchapters', ['chapter_title'], unique=False)
    op.create_index('ix_textbookchapters_chapter_link', 'textbookchapters', ['chapter_link'], unique=False)
    op.create_table('textbooks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('book_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='textbooks_pkey')
    )
    op.create_index('ix_textbooks_title', 'textbooks', ['title'], unique=False)
    op.create_index('ix_textbooks_id', 'textbooks', ['id'], unique=False)
    op.create_index('ix_textbooks_book_link', 'textbooks', ['book_link'], unique=False)
    op.create_index('ix_textbooks_author', 'textbooks', ['author'], unique=False)
    # ### end Alembic commands ###
