"""Add lesson start date

Revision ID: f74cdb609289
Revises: cda6542ce2ba
Create Date: 2024-10-25 13:55:16.110834

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f74cdb609289"
down_revision: Union[str, None] = "cda6542ce2ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lessons", sa.Column("start_date", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lessons", "start_date")
    # ### end Alembic commands ###
